# Generated by Django 5.2.1 on 2025-08-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('history', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('google_maps_embed', models.TextField(help_text='Google Maps embed code')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('about', 'About Section'), ('services', 'Services Section'), ('highlights', 'Highlights Section'), ('testimonials', 'Testimonials Section'), ('contact', 'Contact Section')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package_type', models.CharField(choices=[('wedding', 'Wedding Package'), ('birthday', 'Birthday Package'), ('corporate', 'Corporate Package'), ('reception', 'Reception Package'), ('restaurant', 'Restaurant Package')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(help_text='e.g., 8 hours, 1 day', max_length=50)),
                ('max_guests', models.IntegerField()),
                ('features', models.TextField(help_text='List of features included')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='slider/')),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
